---
- name: Install DNS Server packages
  include_tasks: install.yml

- name: Configure DNS server
  include_tasks: configure.yml

- name: Open DNS port on firewall
  include_tasks: firewall.yml

- name: Ensure DNS service is running
  include_tasks: service.yml

