---
- name: Install and Configure DNS Server
  hosts: dns_servers
  become: yes
  vars_files:
    - ../global_vars/all.yml
  roles:
    - role: roles/common/dns_server
      tasks_from: install
    - role: roles/common/dns_server
      tasks_from: configure
    - role: roles/common/dns_server
      tasks_from: firewall
    - role: roles/common/dns_server
      tasks_from: service
